---
# This kafka compose is from https://gist.github.com/rmoff/fb7c39cc189fc6082a5fbd390ec92b3d
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/01_auth.sql:/docker-entrypoint-initdb.d/01_auth.sql
      - ./db/02_orders.sql:/docker-entrypoint-initdb.d/02_orders.sql
      - ./db/03_products.sql:/docker-entrypoint-initdb.d/03_products.sql
      - ./db/04_data.sql:/docker-entrypoint-initdb.d/04_data.sql

  msproducts:
    image: ms-products:1.0.1
    build: ./ms-products
    networks:
      - default
    depends_on:
      - kafka
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=jdbc:postgresql://db:5432/challenge3_products
      - KAFKA_HOST=kafka:9092

  msorders:
    image: ms-orders:1.0.1
    build: ./ms-orders
    networks:
      - default
    depends_on:
      - kafka
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=jdbc:postgresql://db:5432/challenge3_orders
      - KAFKA_HOST=kafka:9092

  msauth:
    image: ms-auth:1.0.1
    build: ./ms-auth
    networks:
      - default
    depends_on:
      - kafka
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=jdbc:postgresql://db:5432/challenge3_auth
      - KAFKA_HOST=kafka:9092

  msgateway:
    image: ms-gateway:1.0.1
    build: ./ms-gateway
    networks:
      - default
    ports:
      - "8765:8765"
    environment:
      - SPRING_PROFILES_ACTIVE=container

networks:
  default:

volumes:
  db:
