spring:
  application:
    name: ms-orders
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # logging
    hibernate:
      ddl-auto: create-drop # create-drop

server:
  port: 8100
