spring:
  application:
    name: ms-orders
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # logging
    hibernate:
      ddl-auto: create-drop # create-drop
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  my-topics:
    send-topic: products-send
    reply-topic: products-reply
    consumer-group: products-group
    user-send-topic: users-send
    user-reply-topic: users-reply
    user-consumer-group: users-group
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort

server:
  port: 8100
