spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # logging
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: products-group
  my-topics:
    send-topic: products-send
    reply-topic: products-reply
    consumer-group: products-group

server:
  port: 8000
