spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # logging
    hibernate:
      ddl-auto: update
  # TODO - remover ao criar as tables
  sql:
    init:
      mode: always
#  rabbitmq:
#    addresses: ${QUEUE_ADDR}
#    queue: ms-email

server:
  port: 8000
