spring:
  application:
    name: ms-auth
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # logging
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: products-group
  my-topics:
    send-topic: users-send
    reply-topic: users-reply
    consumer-group: products-group

app:
  jwt:
    ExpirationMs: 3600000
    Secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b

server:
  port: 9000