spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-products-doc
          uri: http://localhost:8000
          predicates:
            - Path=/products/v3/api-docs/**
            - Method=GET

        - id: ms-orders-doc
          uri: http://localhost:8100
          predicates:
            - Path=/orders/v3/api-docs/**
            - Method=GET

        - id: ms-products
          uri: http://localhost:8000
          predicates:
            - Path=/products/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - name: JwtFilter

        - id: ms-orders
          uri: http://localhost:8100
          predicates:
            - Path=/orders/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - name: JwtFilter

        - id: ms-auth
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
            - Method=POST, GET

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /auth/v3/api-docs
        name: Authentication Microservice
      - url: /orders/v3/api-docs
        name: Orders Microservice
      - url: /products/v3/api-docs
        name: Products Microservice
app:
  jwt:
    Secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b

server:
  port: 8765
  error:
    # Necessary to show json error messages
    include-message: always

