spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-products
          uri: http://localhost:8000
          predicates:
            - Path=/products/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - name: JwtFilter
        - id: ms-orders
          uri: http://localhost:8100
          predicates:
            - Path=/orders/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - name: JwtFilter
        - id: ms-auth
          uri: http://localhost:9000
          predicates:
              - Path=/auth/**
              - Method=POST

app:
  jwt:
    Secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b

server:
  port: 8765
  error:
    include-message: always # Necessário para mostrar a mensagem no json quando um erro é retornado